# Generated by Django 3.2.4 on 2021-07-25 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('designacao', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nome', models.CharField(max_length=200)),
                ('endereco', models.CharField(default=' ', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FornecedorDeInternet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('link_chamado', models.URLField()),
            ],
            options={
                'verbose_name': 'Fornecedor de Internet',
                'verbose_name_plural': 'Fornecedores de Internet',
            },
        ),
        migrations.CreateModel(
            name='LocalDeAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Local de Atendimento',
                'verbose_name_plural': 'Locais de Atendimento',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chamados', models.CharField(max_length=200)),
                ('data_criacao', models.DateTimeField()),
                ('data_edicao', models.DateTimeField(auto_now=True)),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.escola')),
                ('local', models.ManyToManyField(to='reports.LocalDeAtendimento')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDeComputador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Computador',
                'verbose_name_plural': 'Tipos de Computador',
            },
        ),
        migrations.CreateModel(
            name='TipoDeLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Laboratório',
                'verbose_name_plural': 'Tipos de Laboratório',
            },
        ),
        migrations.CreateModel(
            name='TipoDeProblema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Tipo de Problema',
                'verbose_name_plural': 'Tipos de Problema',
            },
        ),
        migrations.CreateModel(
            name='ParecerTecnico',
            fields=[
                ('relatorio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.relatorio')),
            ],
            options={
                'verbose_name': 'Parecer Técnico',
                'verbose_name_plural': 'Relatórios de Parecer Técnico',
            },
            bases=('reports.relatorio',),
        ),
        migrations.CreateModel(
            name='LinkDeInternet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocidade', models.IntegerField()),
                ('ip_circuito', models.CharField(max_length=20)),
                ('identificador', models.CharField(max_length=20)),
                ('wifi', models.BooleanField(default=True)),
                ('cabo', models.BooleanField(default=True)),
                ('escola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.escola')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.fornecedordeinternet')),
            ],
            options={
                'verbose_name': 'Link de Internet',
                'verbose_name_plural': 'Links de Internet',
            },
        ),
        migrations.AddField(
            model_name='escola',
            name='locais',
            field=models.ManyToManyField(to='reports.LocalDeAtendimento'),
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('numero_inventario', models.CharField(max_length=20, unique=True)),
                ('sistema_operacional', models.CharField(max_length=20)),
                ('funciona', models.CharField(choices=[('funcionando', 'Funcionando'), ('defeituoso', 'Defeituoso')], default='Funcionando', max_length=12)),
                ('cpu_freq', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=20)),
                ('hostname', models.CharField(max_length=20)),
                ('ip', models.GenericIPAddressField()),
                ('mac_address', models.CharField(max_length=20)),
                ('escola', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.escola')),
                ('local', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.localdeatendimento')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.tipodecomputador')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
            },
        ),
        migrations.CreateModel(
            name='StatusDeBaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('obsolescência', 'Obsolescência'), ('consumo', 'Consumo'), ('alienação', 'Alienação'), ('dano', 'Dano'), ('extravio', 'Extravio'), ('desuso', 'Desuso'), ('transferência', 'Transferência'), ('imprestabilidade', 'Imprestabilidade')], default='Imprestabilidade', max_length=20)),
                ('descricao', models.CharField(max_length=200)),
                ('equipamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.computador')),
                ('parecer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.parecertecnico')),
            ],
        ),
        migrations.CreateModel(
            name='RatPadrao',
            fields=[
                ('relatorio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.relatorio')),
                ('descricao', models.CharField(max_length=100)),
                ('solucao', models.TextField(max_length=1000)),
                ('recomendacao', models.BooleanField(default=False)),
                ('equipamentos', models.CharField(blank=True, default='', max_length=200)),
                ('tipo', models.ManyToManyField(to='reports.TipoDeProblema')),
            ],
            options={
                'verbose_name': 'Relatório de Atendimento Técnico',
                'verbose_name_plural': 'Relatórios de Atendimento Técnico',
            },
            bases=('reports.relatorio',),
        ),
        migrations.CreateModel(
            name='RatLaboratorio',
            fields=[
                ('relatorio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.relatorio')),
                ('foto', models.ImageField(blank=True, upload_to='fotosLab')),
                ('equipamentos', models.ManyToManyField(to='reports.Computador')),
                ('tipo', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='reports.tipodelaboratorio')),
            ],
            options={
                'verbose_name': 'Relatório de Laboratório',
                'verbose_name_plural': 'Relatórios de Laboratório',
            },
            bases=('reports.relatorio',),
        ),
    ]
