# Generated by Django 3.2.4 on 2021-07-25 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratpadrao',
            name='descricao',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='statusdebaixa',
            name='motivo',
            field=models.CharField(choices=[('obsolescência', 'Obsolescência'), ('extravio', 'Extravio'), ('imprestabilidade', 'Imprestabilidade'), ('desuso', 'Desuso'), ('alienação', 'Alienação'), ('dano', 'Dano'), ('transferência', 'Transferência'), ('consumo', 'Consumo')], default='Imprestabilidade', max_length=20),
        ),
    ]
