# Generated by Django 3.2.4 on 2021-08-02 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210725_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='bairro',
            field=models.CharField(blank=True, max_length=25),
        ),
        migrations.AddField(
            model_name='escola',
            name='cep',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='escola',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='escola',
            name='telefones',
            field=models.CharField(blank=True, max_length=35),
        ),
        migrations.AlterField(
            model_name='computador',
            name='cpu_freq',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='escola',
            name='endereco',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='statusdebaixa',
            name='motivo',
            field=models.CharField(choices=[('extravio', 'Extravio'), ('desuso', 'Desuso'), ('alienação', 'Alienação'), ('imprestabilidade', 'Imprestabilidade'), ('obsolescência', 'Obsolescência'), ('consumo', 'Consumo'), ('transferência', 'Transferência'), ('dano', 'Dano')], default='Imprestabilidade', max_length=20),
        ),
    ]
