# Generated by Django 3.2.6 on 2021-09-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210829_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(blank=True, choices=[('ap', 'AP'), ('rn', 'RN'), ('pa', 'PA'), ('al', 'AL'), ('ms', 'MS'), ('es', 'ES'), ('go', 'GO'), ('pe', 'PE'), ('sp', 'SP'), ('ba', 'BA'), ('df', 'DF'), ('ma', 'MA'), ('pb', 'PB'), ('mt', 'MT'), ('se', 'SE'), ('sc', 'SC'), ('pr', 'PR'), ('ro', 'RO'), ('ce', 'CA'), ('ac', 'AC'), ('mg', 'MG'), ('rs', 'RS'), ('to', 'TO'), ('rr', 'RR'), ('rj', 'RJ'), ('am', 'AM')], max_length=2),
        ),
        migrations.AlterField(
            model_name='statusdebaixa',
            name='motivo',
            field=models.CharField(choices=[('obsolescência', 'Obsolescência'), ('imprestabilidade', 'Imprestabilidade'), ('desuso', 'Desuso'), ('dano', 'Dano'), ('alienação', 'Alienação'), ('extravio', 'Extravio'), ('transferência', 'Transferência'), ('consumo', 'Consumo')], default='Imprestabilidade', max_length=20),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='tipo',
            field=models.CharField(choices=[('celular', 'Celular'), ('comercial', 'Comercial'), ('residencial', 'Residencial'), ('fixo', 'Fixo')], max_length=20),
        ),
    ]
