# Generated by Django 3.2.4 on 2021-08-12 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20210801_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computador',
            old_name='cpu_freq',
            new_name='processador',
        ),
        migrations.RenameField(
            model_name='ratlaboratorio',
            old_name='equipamentos',
            new_name='computadores',
        ),
        migrations.RenameField(
            model_name='ratpadrao',
            old_name='equipamentos',
            new_name='itens_recomendados',
        ),
        migrations.RenameField(
            model_name='ratpadrao',
            old_name='tipo',
            new_name='problemas',
        ),
        migrations.RenameField(
            model_name='statusdebaixa',
            old_name='equipamento',
            new_name='computador',
        ),
        migrations.RemoveField(
            model_name='computador',
            name='funciona',
        ),
        migrations.AddField(
            model_name='computador',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='computador',
            name='data_edicao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='computador',
            name='funcionando',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='computador',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='data_edicao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='escola',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fornecedordeinternet',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedordeinternet',
            name='data_edicao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedordeinternet',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='linkdeinternet',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='linkdeinternet',
            name='data_edicao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='linkdeinternet',
            name='funcionando',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='linkdeinternet',
            name='local',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.localdeatendimento'),
        ),
        migrations.AddField(
            model_name='linkdeinternet',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ratlaboratorio',
            name='links',
            field=models.ManyToManyField(to='reports.LinkDeInternet'),
        ),
        migrations.AlterField(
            model_name='linkdeinternet',
            name='ip_circuito',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='relatorio',
            name='data_edicao',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='statusdebaixa',
            name='motivo',
            field=models.CharField(choices=[('imprestabilidade', 'Imprestabilidade'), ('dano', 'Dano'), ('consumo', 'Consumo'), ('alienação', 'Alienação'), ('desuso', 'Desuso'), ('obsolescência', 'Obsolescência'), ('extravio', 'Extravio'), ('transferência', 'Transferência')], default='Imprestabilidade', max_length=20),
        ),
    ]
