# Generated by Django 3.2.6 on 2021-09-11 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20210907_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratlaboratorio',
            name='links',
        ),
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(blank=True, choices=[('pa', 'PA'), ('ms', 'MS'), ('se', 'SE'), ('es', 'ES'), ('pr', 'PR'), ('pe', 'PE'), ('rj', 'RJ'), ('mg', 'MG'), ('mt', 'MT'), ('rs', 'RS'), ('ac', 'AC'), ('rr', 'RR'), ('df', 'DF'), ('to', 'TO'), ('rn', 'RN'), ('go', 'GO'), ('ro', 'RO'), ('ma', 'MA'), ('ba', 'BA'), ('pb', 'PB'), ('sc', 'SC'), ('al', 'AL'), ('sp', 'SP'), ('ce', 'CA'), ('am', 'AM'), ('ap', 'AP')], max_length=2),
        ),
        migrations.AlterField(
            model_name='statusdebaixa',
            name='motivo',
            field=models.CharField(choices=[('extravio', 'Extravio'), ('desuso', 'Desuso'), ('obsolescência', 'Obsolescência'), ('transferência', 'Transferência'), ('dano', 'Dano'), ('consumo', 'Consumo'), ('imprestabilidade', 'Imprestabilidade'), ('alienação', 'Alienação')], default='Imprestabilidade', max_length=20),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='ddd',
            field=models.CharField(default='021', max_length=3),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='operadora',
            field=models.CharField(choices=[('claro', 'Claro'), ('tim', 'Tim'), ('vivo', 'Vivo'), ('oi', 'OI')], max_length=20),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='tipo',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('residencial', 'Residencial'), ('celular', 'Celular'), ('fixo', 'Fixo')], max_length=20),
        ),
        migrations.CreateModel(
            name='LinkDeLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wifi', models.BooleanField(default=True)),
                ('cabo', models.BooleanField(default=True)),
                ('funcionando', models.BooleanField(default=True)),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.linkdeinternet')),
                ('ratlab', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reports.ratlaboratorio')),
            ],
        ),
    ]
