# Generated by Django 3.2.4 on 2021-08-12 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20210811_2244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatorio',
            old_name='local',
            new_name='locais',
        ),
        migrations.AlterField(
            model_name='statusdebaixa',
            name='motivo',
            field=models.CharField(choices=[('dano', 'Dano'), ('alienação', 'Alienação'), ('desuso', 'Desuso'), ('transferência', 'Transferência'), ('consumo', 'Consumo'), ('extravio', 'Extravio'), ('obsolescência', 'Obsolescência'), ('imprestabilidade', 'Imprestabilidade')], default='Imprestabilidade', max_length=20),
        ),
    ]
