# Generated by Django 3.2.4 on 2021-08-14 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20210814_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='locais',
            field=models.ManyToManyField(blank=True, to='reports.LocalDeAtendimento'),
        ),
        migrations.AlterField(
            model_name='statusdebaixa',
            name='motivo',
            field=models.CharField(choices=[('dano', 'Dano'), ('alienação', 'Alienação'), ('obsolescência', 'Obsolescência'), ('desuso', 'Desuso'), ('extravio', 'Extravio'), ('consumo', 'Consumo'), ('imprestabilidade', 'Imprestabilidade'), ('transferência', 'Transferência')], default='Imprestabilidade', max_length=20),
        ),
    ]
