# Generated by Django 3.2.4 on 2021-08-24 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20210814_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro', models.CharField(blank=True, max_length=120)),
                ('numero', models.IntegerField(blank=True)),
                ('complemento', models.CharField(blank=True, max_length=120)),
                ('bairro', models.CharField(blank=True, max_length=50)),
                ('cidade', models.CharField(blank=True, max_length=50)),
                ('uf', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, max_length=12)),
                ('geolocalizacao', models.CharField(blank=True, max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('celular', 'Celular'), ('comercial', 'Comercial'), ('residencial', 'Residencial'), ('fixo', 'Fixo')], max_length=20)),
                ('ddd', models.CharField(max_length=2)),
                ('operadora', models.CharField(choices=[('claro', 'Claro'), ('oi', 'OI'), ('vivo', 'Vivo'), ('tim', 'Tim')], max_length=20)),
                ('numero', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='escola',
            name='telefones',
        ),
        migrations.AlterField(
            model_name='statusdebaixa',
            name='motivo',
            field=models.CharField(choices=[('extravio', 'Extravio'), ('dano', 'Dano'), ('transferência', 'Transferência'), ('desuso', 'Desuso'), ('consumo', 'Consumo'), ('imprestabilidade', 'Imprestabilidade'), ('alienação', 'Alienação'), ('obsolescência', 'Obsolescência')], default='Imprestabilidade', max_length=20),
        ),
        migrations.AlterField(
            model_name='escola',
            name='endereco',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reports.endereco'),
        ),
        migrations.AddField(
            model_name='escola',
            name='telefones',
            field=models.ManyToManyField(blank=True, to='reports.Telefone'),
        ),
    ]
