# Generated by Django 3.2.4 on 2021-08-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20210824_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escola',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='escola',
            name='cep',
        ),
        migrations.AlterField(
            model_name='statusdebaixa',
            name='motivo',
            field=models.CharField(choices=[('dano', 'Dano'), ('imprestabilidade', 'Imprestabilidade'), ('alienação', 'Alienação'), ('obsolescência', 'Obsolescência'), ('consumo', 'Consumo'), ('extravio', 'Extravio'), ('desuso', 'Desuso'), ('transferência', 'Transferência')], default='Imprestabilidade', max_length=20),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='operadora',
            field=models.CharField(choices=[('vivo', 'Vivo'), ('oi', 'OI'), ('tim', 'Tim'), ('claro', 'Claro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='tipo',
            field=models.CharField(choices=[('fixo', 'Fixo'), ('comercial', 'Comercial'), ('residencial', 'Residencial'), ('celular', 'Celular')], max_length=20),
        ),
    ]
