# Generated by Django 3.2.4 on 2021-08-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20210824_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusdebaixa',
            name='motivo',
            field=models.CharField(choices=[('desuso', 'Desuso'), ('imprestabilidade', 'Imprestabilidade'), ('extravio', 'Extravio'), ('transferência', 'Transferência'), ('dano', 'Dano'), ('consumo', 'Consumo'), ('alienação', 'Alienação'), ('obsolescência', 'Obsolescência')], default='Imprestabilidade', max_length=20),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='tipo',
            field=models.CharField(choices=[('residencial', 'Residencial'), ('celular', 'Celular'), ('fixo', 'Fixo'), ('comercial', 'Comercial')], max_length=20),
        ),
    ]
