# Generated by Django 3.2.4 on 2021-08-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20210824_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(blank=True, choices=[('ma', 'MA'), ('sc', 'SC'), ('pb', 'PB'), ('rj', 'RJ'), ('sp', 'SP'), ('pa', 'PA'), ('pe', 'PE'), ('mg', 'MG'), ('to', 'TO'), ('ba', 'BA'), ('rr', 'RR'), ('df', 'DF'), ('go', 'GO'), ('am', 'AM'), ('pr', 'PR'), ('ro', 'RO'), ('mt', 'MT'), ('es', 'ES'), ('rs', 'RS'), ('rn', 'RN'), ('ms', 'MS'), ('ce', 'CA'), ('al', 'AL'), ('ap', 'AP'), ('se', 'SE'), ('ac', 'AC')], max_length=2),
        ),
        migrations.AlterField(
            model_name='statusdebaixa',
            name='motivo',
            field=models.CharField(choices=[('desuso', 'Desuso'), ('transferência', 'Transferência'), ('consumo', 'Consumo'), ('dano', 'Dano'), ('imprestabilidade', 'Imprestabilidade'), ('obsolescência', 'Obsolescência'), ('extravio', 'Extravio'), ('alienação', 'Alienação')], default='Imprestabilidade', max_length=20),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='operadora',
            field=models.CharField(choices=[('vivo', 'Vivo'), ('tim', 'Tim'), ('oi', 'OI'), ('claro', 'Claro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='tipo',
            field=models.CharField(choices=[('celular', 'Celular'), ('comercial', 'Comercial'), ('fixo', 'Fixo'), ('residencial', 'Residencial')], max_length=20),
        ),
    ]
