# Generated by Django 3.2.4 on 2021-08-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20210824_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(blank=True, choices=[('ba', 'BA'), ('ma', 'MA'), ('pe', 'PE'), ('go', 'GO'), ('sc', 'SC'), ('mt', 'MT'), ('ms', 'MS'), ('pa', 'PA'), ('pr', 'PR'), ('rr', 'RR'), ('rn', 'RN'), ('es', 'ES'), ('ac', 'AC'), ('ap', 'AP'), ('ro', 'RO'), ('sp', 'SP'), ('se', 'SE'), ('am', 'AM'), ('to', 'TO'), ('rs', 'RS'), ('al', 'AL'), ('df', 'DF'), ('ce', 'CA'), ('pb', 'PB'), ('rj', 'RJ'), ('mg', 'MG')], max_length=2),
        ),
        migrations.AlterField(
            model_name='statusdebaixa',
            name='motivo',
            field=models.CharField(choices=[('consumo', 'Consumo'), ('dano', 'Dano'), ('desuso', 'Desuso'), ('imprestabilidade', 'Imprestabilidade'), ('alienação', 'Alienação'), ('obsolescência', 'Obsolescência'), ('transferência', 'Transferência'), ('extravio', 'Extravio')], default='Imprestabilidade', max_length=20),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='operadora',
            field=models.CharField(choices=[('tim', 'Tim'), ('oi', 'OI'), ('vivo', 'Vivo'), ('claro', 'Claro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='tipo',
            field=models.CharField(choices=[('celular', 'Celular'), ('fixo', 'Fixo'), ('comercial', 'Comercial'), ('residencial', 'Residencial')], max_length=20),
        ),
    ]
