# Generated by Django 3.2.4 on 2021-08-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_auto_20210824_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fornecedordeinternet',
            name='telefone',
        ),
        migrations.AddField(
            model_name='fornecedordeinternet',
            name='telefones',
            field=models.ManyToManyField(blank=True, to='reports.Telefone'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='uf',
            field=models.CharField(blank=True, choices=[('ba', 'BA'), ('am', 'AM'), ('ce', 'CA'), ('rr', 'RR'), ('pa', 'PA'), ('mg', 'MG'), ('ap', 'AP'), ('pb', 'PB'), ('df', 'DF'), ('sc', 'SC'), ('to', 'TO'), ('ms', 'MS'), ('pr', 'PR'), ('rj', 'RJ'), ('rn', 'RN'), ('al', 'AL'), ('go', 'GO'), ('ro', 'RO'), ('rs', 'RS'), ('sp', 'SP'), ('es', 'ES'), ('pe', 'PE'), ('mt', 'MT'), ('ma', 'MA'), ('ac', 'AC'), ('se', 'SE')], max_length=2),
        ),
        migrations.AlterField(
            model_name='statusdebaixa',
            name='motivo',
            field=models.CharField(choices=[('alienação', 'Alienação'), ('consumo', 'Consumo'), ('transferência', 'Transferência'), ('extravio', 'Extravio'), ('obsolescência', 'Obsolescência'), ('desuso', 'Desuso'), ('imprestabilidade', 'Imprestabilidade'), ('dano', 'Dano')], default='Imprestabilidade', max_length=20),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='operadora',
            field=models.CharField(choices=[('oi', 'OI'), ('vivo', 'Vivo'), ('tim', 'Tim'), ('claro', 'Claro')], max_length=20),
        ),
        migrations.AlterField(
            model_name='telefone',
            name='tipo',
            field=models.CharField(choices=[('comercial', 'Comercial'), ('residencial', 'Residencial'), ('celular', 'Celular'), ('fixo', 'Fixo')], max_length=20),
        ),
    ]
